CREATE TABLE IF NOT EXISTS genero_literario (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL
);

INSERT INTO genero_literario (nome) VALUES ('Romance'), ('Fantasia'), ('Suspense');

CREATE TABLE IF NOT EXISTS usuario (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(100) NOT NULL,
    dt_nascimento DATE NOT NULL,
    idade INT NOT NULL,
    genero VARCHAR(20) NOT NULL,
    aceita_newsletter BOOLEAN NOT NULL,
    genero_literario_id INT NOT NULL,
    FOREIGN KEY (genero_literario_id) REFERENCES genero_literario(id)
    );